name: Release

on: 
  push:
    tags:
    - '*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: DeLaGuardo/setup-clojure@13.4
      with:
        cli: latest
    - uses: graalvm/setup-graalvm@v1.4.3
      with:
        # Java version. See examples of supported syntax in the README file.
        java-version: 25
    
    - name: compile uberjar
      run: clojure T:build uberjar
    - name: compile native-image
      
      run: native-image ./target/*.jar --initialize-at-build-time bmm
    - name: release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "./target/bmm"
